### ISSUE TITLE
Running demo issue 

### ISSUE THREAD

**Issue by DicksonCaetano** [Azure-Samples/communication-services-ui-library-maui#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run the azurecallingcomunicationsample

### Any log messages given by the failure
>[monodroid-assembly] open_from_bundles: failed to load assembly Android.Azure.Common.Bindings.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Android.CallingUI.Bindings.dll
Loaded assembly: /data/data/com.azure.communication.ui.calling.mauisampleapp/files/.__override__/Android.Azure.Common.Bindings.dll
Loaded assembly: /data/data/com.azure.communication.ui.calling.mauisampleapp/files/.__override__/Android.CallingUI.Bindings.dll
Resolved pending breakpoint at 'Com.Azure.Android.Communication.Common.CommunicationTokenCredential.cs:74,1' to void Com.Azure.Android.Communication.Common.CommunicationTokenCredential..ctor (string userToken) [0x0006f].
[System.err] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[System.err] SLF4J: Defaulting to no-operation (NOP) logger implementation
[System.err] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
**Java.Lang.IllegalArgumentException:** ''tokenStr' is not a valid token string'

### Expected/desired behavior
>execute both audio/video call

### OS and Version?
> Android and iOS

### Versions
>

### Mention any other details that might be useful
i dont know where the issue is, in the azure console or the app it self! all it does is give exceptions as soon as i put acess token, call id and name. Any help is welcome.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by iaulakh** [comment]
Hi @DicksonCaetano,

Thank you for raising the issue. Could you please provide the following information:
Are you using a Mac or Windows operating system?
Are you encountering the error on Android or iOS?
If possible, please provide a screenshot of the error.

Thank you.
