### ISSUE TITLE
[Bug] The sln does not compile

### ISSUE THREAD

**Issue by AdamDiament** [Azure-Samples/communication-services-ui-library-maui#12]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
> Clone the repo. Run the android sh as instructed to download the jar. Rebuild the sln.

### Any log messages given by the failure
![image](https://github.com/Azure-Samples/communication-services-ui-library-maui/assets/6513834/08a22775-2aef-4703-8e6a-9e98e63771e1)

### Expected/desired behavior
> It builds

### OS and Version?
> Windows 10

**Comment by iaulakh** [comment]
Please reopen if more info is required.
