### ISSUE TITLE
how to receive incoming call

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#13]
can you please provide example how that library can handle incoming call? I understand that need to create eventgrid and register it with incoming phone number. I can not find any examples and I believe this library can handle it as well.

**Comment by vovanb** [comment]
Hi @iaulakh 
could you please update when incoming call sample will be available in MAUI example?

**Comment by iaulakh** [comment]
Hi @vovanb,
We aim to refresh our one-to-one calling samples for MAUI by approximately June 24.

This feature is currently in public preview, and we encourage you to dive into the documentation [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fazure%2Fcommunication-services%2Fhow-tos%2Fui-library-sdk%2Fone-to-one-calling%3Ftabs%3Dkotlin%26pivots%3Dplatform-android&data=05%7C02%7Ciaulakh%40microsoft.com%7Ca3f54612cf114ce8167408dc106e7202%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638403313809326169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nIp1uTLPUZJ1CunEbmzMKugefvH9wfBnfRClqziNHSw%3D&reserved=0) to get started. Experience the ease of integrating high-quality calls into your application today!

Thanks,
Inderpal

**Comment by vovanb** [comment]
@iaulakh  if release of  one-to-one calling sample will be ready on-time?

**Comment by Mohtasim** [comment]
Hi @vovanb, 
Thank you for your query. We have released one-to-one calling. 
Please refer to the QuickStart for the UI Library [QuickStart](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-android) and look at "Set up a 1:N Outgoing Call and Incoming Call Push Notifications" for 1:1 calling setup.
 
Android and iOS versions supporting 1:1 calling: 1.8.0
 
Please reference sample bindings for [Android](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java) and [iOS](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/ios/RNAzureCommunicationUICalling.swift) to explore utilizing APIs from native UI Libraries.

Thank you :)

**Comment by vovanb** [comment]
Hi @Mohtasim thanks for samples, but I was expecting to get same for MAUI and not only pure Android. This is what @iaulakh  wrote before:
`We aim to refresh our one-to-one calling samples for MAUI by approximately June 24.`

**Comment by iaulakh** [comment]
Hi @vovanb, 

MAUI samples have been updated to include 1-to-1 calling. When you clone the repo, you will see a UI to dial other participants.
To receive incoming calls, you need to set up an ACS push notification hub or event grid following the QuickStart.
Since the APIs are the same across native and cross-platform, please refer to the QuickStart APIs to understand the flow. Let us know if you have any questions.
If you need any further adjustments, feel free to let us know!

**Comment by iaulakh** [comment]
Closing as feature is released in 1.8.0.
