### ISSUE TITLE
Rooms Integration

### ISSUE THREAD

**Issue by Strawberrychewy** [Azure-Samples/communication-services-ui-library-maui#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

Can you please tell me how I can integrate this with ACS Rooms for a room call? I can only see Teams and Group calls

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> None

### Any log messages given by the failure
> None

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pavelprystinka** [comment]
Hi @Strawberrychewy ,

Thank you for raising an issue. Currently, the UI library does not support Rooms call in general availability version, but it is available as beta in the Calling UI SDK version 1.3.1-beta.1. In this version you can use RoomsLocator to join Rooms Call, though it is not yet fully functional and Rooms role does not affect user available functionality as it should.

To use 1.3.0-beta.1 you need to modify Calling UI SDK version in:
- iOSMauiBindings/ProxyLibs/CommunicationUI-Proxy/Podfile
- AndroidMauiBindings/downloadJarScript.sh
- AndroidMauiBindings/Android.CallingUI.Bindings/Android.CallingUI.Bindings.csproj

Unfortunately, there is no date we could share when this feature will be available.

Please do not hesitate to reach out if you require further information.

Thanks.

**Comment by LukeStephen** [comment]
any update on when rooms will be fully supported in this? Out of Beta

**Comment by iaulakh** [comment]
Hi @LukeStephen,
Join Rooms call functionality is added to the latest 1.7.0-beta.1 native release. `CallCompositeRoomLocator` is added. Rooms GA of availability is still targeted to the end of June 2024.

**Comment by iaulakh** [comment]
Hi @LukeStephen,
Join Rooms call functionality is added to the latest 1.9.0 release.
