### ISSUE TITLE
AutoJoin Call 

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#23]
Could you help how to skip preview dialog and join group call - similar to press join call button click on preview dialog

**Comment by vovanb** [comment]
@ShaunaSong thanks for example, but where in CommunicationCallingSampleMauiApp i can customize joinGroupCall? for example in ...\CommunicationCallingSampleMauiApp\Platforms\Android\Composite.cs used below
 callComposite.Launch(MainActivity.Instance, remoteOptions, new CallCompositeLocalOptions(personaData));
So will apreciate if you will provide example relevant to **your sample** application

**Comment by vovanb** [comment]
@ShaunaSong  any chance to get answer?

**Comment by iaulakh** [comment]
Hi @vovanb, please look at https://github.com/Azure-Samples/communication-services-ui-library-maui/blob/main/CommunicationCallingSampleMauiApp/JoinCallPage.xaml.cs
 
``` 
_callControlProps.isSkipSetupON = false;
```

**Comment by vovanb** [comment]
thanks it is working now.
