### ISSUE TITLE
[Bug] IOS Maui Binding issue

### ISSUE THREAD

**Issue by EkponborObehi** [Azure-Samples/communication-services-ui-library-maui#24]
> Please provide us with the following information:

> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> 
I'm targeting net8.0-ios framework. The using IOS Maui Binding project reference on the composite file on IOS Platform folder is returning this error
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0246	The type or namespace name 'iOS' could not be found (are you missing a using directive or an assembly reference?
```
![ios](https://github.com/Azure-Samples/communication-services-ui-library-maui/assets/53861200/072c115a-2453-41b6-9ba3-55b03f701af2)

### Minimal steps to reproduce
> clone the repo, add net8.0-ios to the azurecallingcomunicationsample sln.

### Any log messages given by the failure
>The type or namespace name 'iOS' could not be found (are you missing a using directive or an assembly reference?
The type or namespace name 'CommunicationUIProxy' could not be found (are you missing a using directive or an assembly reference?
	

### Expected/desired behavior
> Build and execute successfully for IOS mobile application

### OS and Version?
> IOS , Windows 10 and MACinCloud

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by iaulakh** [comment]
HI @EkponborObehi, The current MAUI iOS bindings require a Mac with XcFramework to build. In the future, we are planning to provide NuGet packages so that Mac is not required for building bindings. We will share updates once we make progress.

**Comment by EkponborObehi** [comment]
Okay thank you for the feedback.
