### ISSUE TITLE
new project reccomendation for Android

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#33]
I want to create own clean project. What is right way to use your example:
 -  should I have in my solution 4 Bindings projects and make reference as you did or you are planning to release nuget package that will include  all bindings can be part of it?
- Should I always manually bring Jars or this Bindings can do it internally?
could you please think about simplest way from new release and maintenance point of view?

**Comment by iaulakh** [comment]
Hi @vovanb ,

We are currently in the planning stages for the NuGet release, and the feature is still in our backlog. Our team expects to start working on NuGet packages early next year.

In the meantime, please refer to the binding samples and create your own binding projects to use in your applications. You can utilize demo app scripts to download dependencies. When we release the new version, you will be able to use the latest .aar file to update your app bindings.

If you need any further information, please let me know.

Thank you.
