### ISSUE TITLE
how to use one-to-one calls in your sample

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#35]
Could you explain how to use one-to-one calls video call from your example?
should it be too Android application? If yes I do not see in code you start listening for incoming call.
Can you please provide step by step guidance how to make one-to-one video call?

**Comment by iaulakh** [comment]
Hi @vovanb,
Please look at [QuickStart](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/one-to-one-calling?tabs=kotlin&pivots=platform-android). You can try demo app code at [link](https://github.com/Azure/communication-ui-library-android/blob/main/azure-communication-ui/demo-app/src/calling/java/com/azure/android/communication/ui/callingcompositedemoapp/CallCompositeManager.kt).

**Comment by vovanb** [comment]
Hi @iaulakh 
thanks for the reference, but I would like to try your demo communication-services-ui-library-maui.
In your [JoinCallPage.xaml](https://github.com/Azure-Samples/communication-services-ui-library-maui/blob/main/CommunicationCallingSampleMauiApp/JoinCallPage.xaml) you have tab for setup onetoNCall. But I do not see start listening for incoming call in CommunicationCallingSampleMauiApp sample.
Should it  work? What scenario your sample expect - start call on MAUI and answer to call where?
Can you please complete MAUI sample so answer to  onetoNCall will in CommunicationCallingSampleMauiApp.

**Comment by iaulakh** [comment]
Hi @vovanb, closing as per discussion. Please look at [QuickStart](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/one-to-one-calling?tabs=kotlin&pivots=platform-android).
