### ISSUE TITLE
how to hide video button from user screen

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#36]
I want to control which buttons available and which to hide during setup of Video Call.
For example I want to hide all buttons from the Video call screen.

**Comment by pavelprystinka** [comment]
Hi @vovanb,
You may use `CallCompositeAudioVideoMode.AUDIO_ONLY`. Please see this [tutorial](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/audio-only-mode?pivots=programming-language-kotlin)

To hide all buttons - this feature is currently in development and expected in upcoming release.

Thanks

**Comment by vovanb** [comment]
@pavelprystinka 
I want to have Video call but I want to hide Camera, Mic, Speaker, Hangup buttons or makes then disabled.
so your suggestion with AUDIO_ONLY seems not relevant

**Comment by pavelprystinka** [comment]
Hi @vovanb,

Hiding/disabling buttons is currently in development and will be available in one of upcoming releases. I do not have an exact release date to share with you, but it should be within a month or so.

Thanks

**Comment by vovanb** [comment]
@pavelprystinka do you have update about control video buttons?

**Comment by pavelprystinka** [comment]
@vovanb 
Buttons configuration feature is now released.
Please see this this article for details: https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/button-injection?tabs=kotlin&pivots=platform-android

**Comment by vovanb** [comment]
@pavelprystinka - how I can hide all buttons? Can you please provide example based on that MAUI project?
