### ISSUE TITLE
CallWithChat .Net Maui

### ISSUE THREAD

**Issue by EkponborObehi** [Azure-Samples/communication-services-ui-library-maui#37]
Please how can one use call with chat Composite for .Net Maui?

### OS and Version?
> Android, IOS

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ShaunaSong** [comment]
Hello @EkponborObehi,
 
Thanks for reaching out! Currently, the Call with Chat Composite has not been released. We are planning to release this feature tentatively next year. We appreciate your interest and patience.
 
We'll keep the community updated on our progress. If you have any more questions or need further assistance in the meantime, feel free to ask.
 
Best regards,
 
Shauna

**Comment by EkponborObehi** [comment]
> Hello @EkponborObehi,
> 
> Thanks for reaching out! Currently, the Call with Chat Composite has not been released. We are planning to release this feature tentatively next year. We appreciate your interest and patience.
> 
> We'll keep the community updated on our progress. If you have any more questions or need further assistance in the meantime, feel free to ask.
> 
> Best regards,
> 
> Shauna

Good day @ShaunaSong  thanks for your feedback. Looking forward to this! 

Meanwhile I reported an issue here [.](https://github.com/Azure-Samples/communication-services-ui-library-maui/issues/38) Need your assistance

**Comment by EkponborObehi** [comment]
Hello @ShaunaSong, also for Android, i saw one can change the setupview data by calling  
CallCompositeSetupScreenViewData setupviewData = null;
setupviewData = new CallCompositeSetupScreenViewData();
setupviewData.SetTitle("xxxx"); in the composite file

How can one set the title on IOS? I can't see the option...

**Comment by ShaunaSong** [comment]
Hello @EkponborObehi,

In iOS, we use the same setup in `LocalOptions` with the object name `SetupScreenViewData`. You can utilize it as follows:

```swift
let setupScreenViewData = SetupScreenViewData(title: "", subtitle: "")
let localOptions = LocalOptions(participantViewData: participantViewData, setupScreenViewData: setupScreenViewData, ...)
```

If you have any further questions, please feel free to ask.

Thanks,  
Shauna

**Comment by EkponborObehi** [comment]
Good day @ShaunaSong, so this is what i'm trying to explain, if you look at this screenshot on the Composite file on the IOS

![composite](https://github.com/user-attachments/assets/77ef74b9-dcd4-4a71-8e3e-dc3048183c10)

The properties here are different from the android set up, for participantViewData property for instance, it's using CommunicationPersonaDataProxy and so on. There  is no SetupScreenViewData property....

**Comment by pavelprystinka** [comment]
Hi @EkponborObehi 
In this sample project we do not have all possible configurations settings utilized. But in your application you may extend it and use CallComposite's public API in full.
