### ISSUE TITLE
Elaborate "Known Issues" for Windows

### ISSUE THREAD

**Issue by verzada** [Azure-Samples/communication-services-ui-library-maui#40]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Setting up the Sample library in Windows with Visual Studio 2022

### Any log messages given by the failure
> 

This was my error list in Visual Studio, didn't give a hint that this could be solved by making the path shorter.

![image](https://github.com/user-attachments/assets/673f1792-d847-426e-8efd-7177232ad021)

### Expected/desired behavior
> Just building

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

Replication of issue https://github.com/Azure-Samples/communication-services-ui-library-maui/issues/29

I'd like to see a bit more elaboration for the error that occurs when the path to the project is too long in Windows. I didn't see ```Severity Code Description Project Line Supression State``` error, only that the .flat files were unavailable.

Perhaps a line under the last bulletpoint, mentioning missing .flat files is a symptom of the path being too long.

**Comment by iaulakh** [comment]
Hi @verzada ,

Thank you for reporting the issue. The [Known Issues](https://github.com/Azure-Samples/communication-services-ui-library-maui/wiki/Known-Issues) have been updated, and I've also added a link to the MAUI known issues. Please let me know if you have any further questions.
