### ISSUE TITLE
Java.Lang.NullPointerException on call disconnect

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#42]
Periodically receive exception on Video call disconnect:
`[gralloc4] @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
[SensorManager] unregisterListener
[TelecomFramework] TelecomConnectionService: onAvailableCallEndpointsChanged TC@27_1: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.oACEC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onAvailableCallEndpointsChanged - Cannot find conference TC@27_1: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.oACEC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onCallEndpointChanged TC@27_1 [CallEndpoint Name: Динамик телефона, Type: EARPIECE, Identifier: 7d7eb5c2-a3f6-444c-951d-6d1023c2e8b5]: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.oCEC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onCallEndpointChanged - Cannot find conference TC@27_1: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.oCEC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onMuteStateChanged TC@27_1 false: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.oMSC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onMuteStateChanged - Cannot find conference TC@27_1: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.oMSC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onAudioStateChanged TC@27_1 [AudioState isMuted: false, route: EARPIECE, supportedRouteMask: EARPIECE, SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.cASC->H.CS.cASC(cMT/cast)@E-LGU
[TelecomFramework] TelecomConnectionService: onCallAudioStateChanged - Cannot find conference TC@27_1: (CSW.sDc->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.cASC->H.CS.cASC(cMT/cast)@E-LGU
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com..., PID: 12200
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.TextureView.setTransform(android.graphics.Matrix)' on a null object reference
[AndroidRuntime] 	at com.azure.android.communication.calling.VideoStreamView.lambda$ScaleTextureView$0$com-azure-android-communication-calling-VideoStreamView(VideoStreamView.java:135)
[AndroidRuntime] 	at com.azure.android.communication.calling.VideoStreamView$$ExternalSyntheticLambda2.run(Unknown Source:4)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:958)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:230)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:319)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8919)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
**Java.Lang.NullPointerException:** 'Attempt to invoke virtual method 'void android.view.TextureView.setTransform(android.graphics.Matrix)' on a null object reference'

Android 14-API 34
`

**Comment by vovanb** [comment]
@iaulakh 
can you please check that issue - please note that it happen if I press hangup very fast, right after call started

**Comment by iaulakh** [comment]
Please update to https://mvnrepository.com/artifact/com.azure.android/azure-communication-calling/2.11.0-beta.1.

**Comment by vovanb** [comment]
sorry @iaulakh how I can update SDK in existing project?

**Comment by iaulakh** [comment]
Please use  ```implementation 'com.azure.android:azure-communication-calling:2.11.0-beta.1'```.

**Comment by vovanb** [comment]
well, I modified  attached 
[downloadJarScript .txt](https://github.com/user-attachments/files/16761695/downloadJarScript.txt) to use azure-communication-calling-2.11.0-beta.1.aar
then in CommunicationCallingSampleMauiApp.csproj and in AndroidMauiBindings\Android.CallingUI.Bindings\Android.CallingUI.Bindings.csproj changed to use azure-communication-calling-2.11.0-beta.1.aar

and then I got below errors on compile:

```
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Skype.Android.Video.HW.Extension.Decoder.VideoSampleDecoderExtension.cs(23,60,23,142): error CS0738: 'VideoSampleDecoderExtension.Factory' does not implement interface member 'IVideoDecoderExtensionFactory.Create(int)'. 'VideoSampleDecoderExtension.Factory.Create(int)' cannot implement 'IVideoDecoderExtensionFactory.Create(int)' because it does not have the matching return type of 'IVideoDecoderExtension'.
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Microsoft.DL.Video.Capture.Api.FpsRange.cs(20,60,20,89): error CS0535: 'FpsRange' does not implement interface member 'IComparable.CompareTo(Object)'
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Microsoft.DL.Video.Utils.Resolution.cs(20,93,20,122): error CS0535: 'Resolution' does not implement interface member 'IComparable.CompareTo(Object)'
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Skype.Android.Video.HW.Format.Resolution.cs(20,93,20,122): error CS0535: 'Resolution' does not implement interface member 'IComparable.CompareTo(Object)'
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Skype.Android.Video.HW.Extension.Encoder.VideoCameraEncoderExtension.cs(20,23,20,50): error CS0534: 'VideoCameraEncoderExtension' does not implement inherited abstract member 'AbstractVideoEncoderExtension.DoCreateEncoder(string?)'
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Skype.Android.Video.HW.Extension.Encoder.VideoSampleEncoderExtension.cs(20,23,20,50): error CS0534: 'VideoSampleEncoderExtension' does not implement inherited abstract member 'AbstractVideoEncoderExtension.DoCreateEncoder(string?)'
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Skype.Android.Video.HW.Extension.Encoder.VideoSampleEncoderExtension.cs(23,60,23,142): error CS0738: 'VideoSampleEncoderExtension.Factory' does not implement interface member 'IVideoEncoderExtensionFactory.Create(int)'. 'VideoSampleEncoderExtension.Factory.Create(int)' cannot implement 'IVideoEncoderExtensionFactory.Create(int)' because it does not have the matching return type of 'IVideoEncoderExtension'.
csuilib-maui\AndroidMauiBindings\Android.CallingUI.Bindings\obj\Debug\net8.0-android\generated\src\Com.Skype.Android.Video.HW.Extension.Encoder.VideoTextureEncoderExtension.cs(20,23,20,51): error CS0534: 'VideoTextureEncoderExtension' does not implement inherited abstract member 'AbstractVideoEncoderExtension.DoCreateEncoder(string?)'
```
should I update all packages ?

**Comment by iaulakh** [comment]
Hi @vovanb ,
Thank you for trying the latest beta SDK. We will attempt to reproduce the issue on our side and will share our findings and resolution.

**Comment by iaulakh** [comment]
Hi @vovanb 
Please try [Commit](https://github.com/Azure-Samples/communication-services-ui-library-maui/commit/acd13927bfd1ff412fb3a6b3926d27043fa8e194).

**Comment by vovanb** [comment]
Hi @iaulakh 
still exist issue - You added azure-communication-calling-2.11.0-beta.1.aar, but the previous name was azure-communication-**ui**-calling-1.10.0-beta.1.aar

In new downloadJarScript.sh exist reference to
` curl "https://repo1.maven.org/maven2/com/azure/android/azure-communication-ui-calling/1.10.0/azure-communication-ui-calling-1.10.0.aar" --output azure-communication-ui-calling-1.10.0.aar
`
and also to 
`curl  "https://repo1.maven.org/maven2/com/azure/android/azure-communication-calling/2.11.0-beta.1/azure-communication-calling-2.11.0-beta.1.aar" --output azure-communication-calling-2.11.0-beta.1.aar`

Now when I compile I got:
`5>\MauiApp\Platforms\Android\Composite.cs(5,39,5,41): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Com.Azure.Android.Communication' (are you missing an assembly reference?)
5>\MauiApp\Platforms\Android\Composite.cs(6,39,6,41): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Com.Azure.Android.Communication' (are you missing an assembly reference?)
5>\MauiApp\Platforms\Android\RemoteParticipantJoinedHandler.cs(3,39,3,41): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Com.Azure.Android.Communication' (are you missing an assembly reference?)
5>\MauiApp\Platforms\Android\RemoteParticipantJoinedHandler.cs(4,39,4,41): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Com.Azure.Android.Communication' (are you missing an assembly reference?)
5>MauiApp\Platforms\Android\RemoteParticipantJoinedHandler.cs(10,71,10,97): error CS0246: The type or namespace name 'ICallCompositeEventHandler' could not be found (are you missing a using directive or an assembly reference?)
5>`

**Comment by iaulakh** [comment]
Hi @vovanb ,
Please look at [commit](https://github.com/Azure-Samples/communication-services-ui-library-maui/commit/acd13927bfd1ff412fb3a6b3926d27043fa8e194).

![image](https://github.com/user-attachments/assets/326730ac-938a-4a26-9df8-13622628f5d9)

**Comment by vovanb** [comment]
compiled ok - no crash so far

**Comment by vovanb** [comment]
@iaulakh 
reopened case again - I found another problem that speaker is not selected all the time - sometime it is, but sometime I need to change speaker-android->speaker and then it is working
Could you please help?

**Comment by iaulakh** [comment]
Hi @vovanb,
Please look at [Default options for camera and microphone configuration](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/skip-setup-screen?tabs=kotlin&pivots=platform-android#default-options-for-camera-and-microphone-configuration).
