### ISSUE TITLE
group video call started but sometime not on the Android device's speaker

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-maui#43]
### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
make group call - sometime first caller do not hear second party, sometime second party joined after first one do not hear caller on speaker , the call is in Android .
playing with speaker : during call  change speaker->android->speaker fix the problem

### Expected/desired behavior
call should be started on speaker for all members of group call

### OS and Version?
Android 14

**Comment by iaulakh** [comment]
Thanks @vovanb. We are working on reproducing the issue and will provide an update once it has been resolved.

**Comment by vovanb** [comment]
@iaulakh many thanks for update. Please let me know if you need logs - I can upload it to your secured URL - did not want to put it on public repository

**Comment by iaulakh** [comment]
Hi @vovanb,
Thank you for reporting this issue. I have tried a few times, and the calls always go on speaker until the user changes to phone.
Could you please share the following information?
- When a participant joins a call, is the speaker or phone option visible in the audio selection?
- Are you able to reproduce this issue consistently?

**Comment by vovanb** [comment]
Hi @iaulakh 
in audio selection visible speaker and Android. Speaker shown as selected, but audio is not coming to it
Yes I able to reproduce it almost every call

**Comment by iaulakh** [comment]
Hi @vovanb,
Would it be possible for you to share a video with the full device screen? It would be awesome to see a demo from the composite launch to the end, including the issue.

**Comment by vovanb** [comment]
provided

**Comment by iaulakh** [comment]
Thanks @vovanb. Replied to email with latest beta drops and APIs.
