### ISSUE TITLE
Is there a required XCode Version for this to work?

### ISSUE THREAD

**Issue by EkponborObehi** [Azure-Samples/communication-services-ui-library-maui#44]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report 
```

### Minimal steps to reproduce
> Follow the steps as described on the readme file and run the ./iOSFramework.sh -d script

### Any log messages given by the failure

> When i run the project, it keeps crashing and showing this error on the log

 dyld[10550]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E

  Referenced from: <00A85B80-B310-317A-B63E-0B63AD669A57> /Users/user263933/Library/Developer/CoreSimulator/Devices/75E69B9D-E5AF-408E-87B4-F43038E26567/data/Containers/Bundle/Application/3535E7F5-D6C2-4F23-B33B-3C2C9A4C080E/CommunicationCallingSampleMauiApp.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling

  Expected in:     <52A480D8-7E2A-3FD8-B329-8470ED0484A6> /Users/user263933/Library/Developer/CoreSimulator/Devices/75E69B9D-E5AF-408E-87B4-F43038E26567/data/Containers/Bundle/Application/3535E7F5-D6C2-4F23-B33B-3C2C9A4C080E/CommunicationCallingSampleMauiApp.app/Frameworks/AzureCommunicationCommon.framework/AzureCommunicationCommon

### Expected/desired behavior
> For the project to run on IOS simulators and devices

### OS and Version?
>  macOS (Sonoma) 14.6.1

### Versions
> XCode 16

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pavelprystinka** [comment]
@EkponborObehi 

Thank you for pointing this issue.
We are now working on it and will be back with a solution soon.

**Comment by EkponborObehi** [comment]
> @EkponborObehi
> 
> Thank you for pointing this issue. We are now working on it and will be back with a solution soon.

Thank you @pavelprystinka

**Comment by iaulakh** [comment]
Hi @EkponborObehi,
Please look at latest versions of MAUI and .NET to support Xcode 16.0. [Xcode 16.0 Support for .NET 8/9 and MAUI](https://github.com/xamarin/xamarin-macios/issues/20802).

**Comment by EkponborObehi** [comment]
Hi @iaulakh, thank you! This works fine. However, I’m currently having another issue when I run the app and try to join a call which I opened on the link below. This issue is common in the latest releases. The release with 1.6.0 doesn’t have that same problem and it occurs on both Android and IOS. 

 https://github.com/Azure-Samples/communication-services-ui-library-maui/issues/46

**Comment by iaulakh** [comment]
ok, thanks. Please close this issue. We will look at another issue.
