### ISSUE TITLE
This is not what people are looking for

### ISSUE THREAD

**Issue by MhAllan** [Azure-Samples/communication-services-ui-library-maui#8]
This is jar binding, a messy unfunctional code that renders very rigid views which are not customizable. That is not what we are looking for. for years we are asking for C# library that runs on MAUI so we deal with low level details like CallClient and CallAgent .. etc. and be able to render the video anywhere we like with the controls we like. not with this composite thing. Simply, we want something like this but for C# and MAUI: https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-web

**Comment by iaulakh** [comment]
Hello MhAllan,

Thank you for reaching out. I appreciate your interest in the UI libraries showcased in the repository [Azure Communication UI Library for Android](https://github.com/Azure/communication-ui-library-android), which offer support for .NET MAUI. These UI libraries provide customizable components for common calling interactions and are available as open source.

It appears that you are exploring [native calling SDKs](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-android) and wish to create your own unique UI experience. Unfortunately, as of now, there are no native SDK bindings specifically designed for .NET MAUI. However, you can refer to the bindings samples available in the repository to understand how to create bindings for native SDKs.

For comprehensive insights into MAUI bindings and their integration, I recommend visiting the following [link](https://learn.microsoft.com/en-us/events/dotnetconf-focus-on-maui/binding-native-libraries-for-dotnet-maui).

If you have any further questions or require additional assistance, please feel free to ask.

Best regards.

**Comment by iaulakh** [comment]
Hello MhAllan, please reopen if more info is required.
